# Docs at https://github.com/bitnami/charts/blob/master/bitnami/nginx/values.yaml
#image:
#  repository: sparkfabrik/gopoc-app1
#  tag: 1.0

# NGINX Service properties
#
service:
  # Service type
  type: ClusterIP
  # HTTP Port
  port: 80

# Configure the ingress resource that allows you to access the
# Nginx installation. Set up the URL
# ref: http://kubernetes.io/docs/user-guide/ingress/
#
ingress:
  enabled: true
  # When the ingress is enabled, a host pointing to this will be created
  hostname: app1.local
  annotations:
    kubernetes.io/ingress.class: nginx
