apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopoc-app1-nginx
  namespace: gopoc-app1
spec:
  template:
    spec:
      containers:
      - name: nginx
        image: aypx/gitops-poc-app-1:main-3c62385-1620140527 # {"$imagepolicy": "flux-system:app-application-1"}
