---
# Source: nginx/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gopoc-app1-nginx
  namespace: kube-prometheus-stack
  labels:
    app.kubernetes.io/name: nginx
    helm.sh/chart: nginx-8.9.0
    app.kubernetes.io/instance: gopoc-app1
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: gopoc-app1
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - gopoc-app1
